# Site settings
title: TeenTech NY
email: contact@teentechny.org
description: "TeenTech Yeah"
baseurl: ""
url: "http://teentechny.org"
twitter_username: teentechny
facebook_username:  OfficialTeenTechNY

# Build settings
markdown: kramdown
permalink: pretty
pygments: true

sass:
    sass_dir: css/
    