# Site settings
title: TeenTech NY
email: contact@teentechny.org
description: "TeenTech is an interactive tech community run by teens for teens."
baseurl: "http://teentechny.org"
url: "http://teentechny.org"
logo_url: "http://teentechny.org/images/ttny_solid_logo"
twitter_username: teentechny
facebook_username:  OfficialTeenTechNY

# Build settings
markdown: kramdown
permalink: pretty
pygments: true

sass:
    sass_dir: css/
    